export enum ErrorIds {
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  GENERIC_BAD_REQUEST = "GENERIC_BAD_REQUEST",
  WRONG_OBJECT_ID_FORMAT = "WRONG_OBJECT_ID_FORMAT",
  WRONG_EMAIL_FORMAT = "WRONG_EMAIL_FORMAT",
  WRONG_PASSWORD_LENGTH = "WRONG_PASSWORD_LENGTH",
  WRONG_USER_LIST_FORMAT = "WRONG_USER_LIST_FORMAT",
  NOT_AUTHENTICATED = "NOT_AUTHENTICATED",
  NOT_AUTHORIZED = "NOT_AUTHORIZED",

  FAILED_TO_DELETE_RESOURCE = "FAILED_TO_DELETE_RESOURCE",
  FAILED_TO_UPDATE_RESOUCE = "FAILED_TO_UPDATE_RESOURCE",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
}
