export const defaultWorkflows = [
  {
    domain: "personal",
    title: "personal planning",
    description: "Organizing personal priorities, routines, and commitments.",
    categories: [
      "annual goals",
      "quarterly goals",
      "monthly goals",
      "weekly goals",
      "daily planning",
      "priority setting",
      "time blocking",
      "calendar review",
      "appointment planning",
      "deadline tracking",
      "habit setup",
      "habit review",
      "routine design",
      "routine optimization",
      "personal kanban",
      "task batching",
      "focus sessions",
      "deep work",
      "break planning",
      "energy planning",
      "morning routine",
      "evening routine",
      "weekend planning",
      "travel planning",
      "packing plans",
      "event planning",
      "birthday planning",
      "family planning",
      "relationship checkins",
      "personal journaling",
      "reflection sessions",
      "decision logs",
      "idea capture",
      "personal research",
      "reading list",
      "course planning",
      "skill roadmap",
      "budget planning",
      "savings planning",
      "expense review",
      "bill schedule",
      "subscription review",
      "document organization",
      "inbox zero",
      "follow up tracking",
      "call planning",
      "message planning",
      "errands planning",
      "shopping plans",
      "contingency planning",
    ],
  },
  {
    domain: "personal",
    title: "home management",
    description:
      "Household upkeep, logistics, and recurring non-work operations.",
    categories: [
      "home cleaning",
      "deep cleaning",
      "laundry",
      "dishwashing",
      "trash and recycling",
      "decluttering",
      "organizing storage",
      "pantry organization",
      "grocery inventory",
      "grocery shopping",
      "meal planning",
      "meal prep",
      "cooking",
      "kitchen maintenance",
      "appliance maintenance",
      "hvac maintenance",
      "plumbing checks",
      "electrical checks",
      "safety checks",
      "home repairs",
      "contractor coordination",
      "service appointments",
      "pest control",
      "garden care",
      "lawn care",
      "plant care",
      "pet care logistics",
      "household budgeting",
      "utility tracking",
      "utility payments",
      "mortgage or rent",
      "insurance management",
      "warranty tracking",
      "furniture maintenance",
      "home office setup",
      "moving preparation",
      "room redesign",
      "seasonal maintenance",
      "winter preparation",
      "summer preparation",
      "emergency kit",
      "household paperwork",
      "document filing",
      "package management",
      "donation management",
      "recycling drops",
      "chore scheduling",
      "chore delegation",
      "inventory restock",
      "home automation",
    ],
  },
  {
    domain: "personal",
    title: "health and wellbeing",
    description: "Physical and mental wellbeing activities and improvements.",
    categories: [
      "workout planning",
      "strength training",
      "cardio sessions",
      "mobility training",
      "stretching",
      "yoga practice",
      "pilates practice",
      "running training",
      "cycling training",
      "sports training",
      "recovery sessions",
      "rest day planning",
      "sleep routine",
      "sleep tracking",
      "hydration tracking",
      "nutrition planning",
      "calorie planning",
      "macro tracking",
      "meal quality review",
      "supplement planning",
      "medical appointments",
      "preventive screenings",
      "medication tracking",
      "symptom tracking",
      "physiotherapy exercises",
      "posture correction",
      "breathing exercises",
      "meditation",
      "mindfulness practice",
      "stress management",
      "anxiety management",
      "mental health journaling",
      "therapy homework",
      "digital detox",
      "outdoor time",
      "sunlight exposure",
      "step goals",
      "weight tracking",
      "body metrics",
      "habit accountability",
      "addiction reduction",
      "ergonomic adjustments",
      "eye care breaks",
      "dental care",
      "skin care routine",
      "chronic condition management",
      "health education",
      "community support",
      "wellbeing retrospectives",
      "motivation planning",
    ],
  },
  {
    domain: "software development",
    title: "backend",
    description:
      "Server-side architecture and implementation for APIs and services.",
    categories: [
      "requirements analysis",
      "domain modeling",
      "api contract design",
      "rest endpoint design",
      "graphql schema design",
      "rpc interface design",
      "authentication flow",
      "authorization rules",
      "role permissions",
      "input validation",
      "serialization mapping",
      "business logic implementation",
      "service layer design",
      "repository layer",
      "database schema design",
      "migration scripts",
      "query optimization",
      "indexing strategy",
      "caching strategy",
      "background jobs",
      "queue processing",
      "event driven workflows",
      "message broker integration",
      "third party integrations",
      "webhook handling",
      "file storage integration",
      "payment integration",
      "email service integration",
      "audit logging",
      "observability hooks",
      "error handling",
      "retry and idempotency",
      "rate limiting",
      "feature flags",
      "config management",
      "secret management",
      "api versioning",
      "backward compatibility",
      "unit testing",
      "integration testing",
      "contract testing",
      "load testing",
      "performance profiling",
      "security review",
      "vulnerability patching",
      "refactoring",
      "technical debt cleanup",
      "bug triage",
      "bug fixing",
      "code review updates",
    ],
  },
  {
    domain: "software development",
    title: "frontend",
    description:
      "Client-side implementation focused on UX, UI, and interaction.",
    categories: [
      "product requirement review",
      "ux flow mapping",
      "information architecture",
      "wireframe implementation",
      "design system alignment",
      "component architecture",
      "reusable components",
      "page layout",
      "routing setup",
      "state modeling",
      "state management",
      "form implementation",
      "form validation",
      "data fetching",
      "query caching",
      "optimistic updates",
      "loading states",
      "empty states",
      "error states",
      "accessibility semantics",
      "keyboard navigation",
      "screen reader support",
      "responsive design",
      "mobile optimization",
      "tablet optimization",
      "desktop optimization",
      "theming support",
      "typography tuning",
      "iconography updates",
      "animation implementation",
      "micro interaction polish",
      "performance optimization",
      "bundle size reduction",
      "code splitting",
      "image optimization",
      "seo metadata",
      "internationalization",
      "localization qa",
      "unit testing",
      "component testing",
      "end to end testing",
      "visual regression",
      "cross browser testing",
      "bug reproduction",
      "bug fixing",
      "refactoring",
      "analytics tracking",
      "consent handling",
      "release hardening",
      "code review updates",
    ],
  },
  {
    domain: "software development",
    title: "full-stack",
    description:
      "End-to-end feature delivery across frontend and backend layers.",
    categories: [
      "feature discovery",
      "technical scoping",
      "architecture decisions",
      "api and ui contract",
      "db schema and ui model",
      "endpoint implementation",
      "frontend integration",
      "auth end to end",
      "permission enforcement",
      "validation end to end",
      "file upload flow",
      "payment flow",
      "notification flow",
      "search flow",
      "filtering and sorting",
      "pagination flow",
      "transaction handling",
      "consistency checks",
      "migration rollout",
      "seed data updates",
      "telemetry integration",
      "logging end to end",
      "tracing end to end",
      "monitoring dashboards",
      "alert definitions",
      "error budget tracking",
      "performance baseline",
      "latency optimization",
      "throughput optimization",
      "caching end to end",
      "ci pipeline updates",
      "preview environment",
      "qa handoff",
      "acceptance testing",
      "regression testing",
      "staging validation",
      "release planning",
      "rollout strategy",
      "feature flag rollout",
      "rollback planning",
      "post release checks",
      "bug triage",
      "hotfix delivery",
      "documentation updates",
      "runbook updates",
      "refactoring",
      "technical debt cleanup",
      "stakeholder demo",
      "retrospective action items",
      "code review updates",
    ],
  },
  {
    domain: "software development",
    title: "devops",
    description:
      "Infrastructure, delivery pipelines, observability, and operations.",
    categories: [
      "infrastructure design",
      "infrastructure as code",
      "terraform modules",
      "cloud networking",
      "vpc and subnet setup",
      "dns management",
      "tls certificate management",
      "load balancer config",
      "containerization",
      "image hardening",
      "kubernetes manifests",
      "helm chart updates",
      "cluster provisioning",
      "autoscaling rules",
      "secrets management",
      "config management",
      "ci pipeline design",
      "ci pipeline maintenance",
      "cd pipeline design",
      "cd pipeline maintenance",
      "build cache optimization",
      "artifact management",
      "environment promotion",
      "release orchestration",
      "blue green deployment",
      "canary deployment",
      "rollback automation",
      "database backup",
      "disaster recovery",
      "observability stack",
      "metrics instrumentation",
      "log aggregation",
      "distributed tracing",
      "alert tuning",
      "on call rotation",
      "incident response",
      "postmortem analysis",
      "sla and slo tracking",
      "security scanning",
      "dependency patching",
      "runtime hardening",
      "access control",
      "iam policy review",
      "cost optimization",
      "capacity planning",
      "compliance checks",
      "runbook maintenance",
      "platform documentation",
      "developer enablement",
      "toil reduction",
    ],
  },
  {
    domain: "marketing",
    title: "marketing campaigns",
    description: "Planning and executing marketing campaigns and promotions.",
    categories: [
      "campaign planning",
      "content calendar",
      "social media",
      "seo",
      "paid advertising",
      "email campaigns",
      "analytics and reporting",
      "a/b testing",
      "influencer outreach",
      "event promotion",
    ],
  },
  {
    domain: "sales",
    title: "sales pipeline",
    description: "Managing leads and opportunities through the sales funnel.",
    categories: [
      "lead capture",
      "lead qualification",
      "outreach cadence",
      "demo scheduling",
      "proposal creation",
      "negotiation",
      "contract signing",
      "customer onboarding",
      "pipeline reviews",
      "forecasting",
    ],
  },
  {
    domain: "design",
    title: "design process",
    description: "Design discovery, prototyping, and handoff workflows.",
    categories: [
      "research and discovery",
      "wireframing",
      "prototyping",
      "visual design",
      "design reviews",
      "accessibility audit",
      "component library",
      "usability testing",
      "dev handoff",
      "iteration",
    ],
  },
  {
    domain: "operations",
    title: "operations and support",
    description:
      "Internal operations, vendor management, and support workflows.",
    categories: [
      "vendor management",
      "procurement",
      "facilities",
      "policy updates",
      "compliance",
      "sla monitoring",
      "vendor invoicing",
      "risk assessment",
      "business continuity",
      "onboarding",
    ],
  },
  {
    domain: "finance",
    title: "finance and accounting",
    description: "Budgeting, reporting, and financial operations.",
    categories: [
      "budgeting",
      "month end close",
      "invoicing",
      "payroll",
      "expense reports",
      "tax filings",
      "financial reporting",
      "cash flow management",
      "forecasting",
      "audit preparation",
    ],
  },
];
