import type { Metadata } from "next";
import "./globals.css";
import "@/i18n";

import { Geist, Geist_Mono, Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import type { ReactNode, JSX } from "react";
import { AuthGuard } from "@/components/auth-guard";
import { AuthSessionProvider } from "@/providers/auth-session-provider";
import { AuthStoreInitializer } from "@/providers";
import { ReactQueryProvider } from "@/providers/query-client";
import { SidebarWrapper } from "@/components/sidebar-wrapper";

const APP_METADATA_TITLE = "Create Next App";
const APP_METADATA_DESCRIPTION = "Generated by create next app";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: APP_METADATA_TITLE,
  description: APP_METADATA_DESCRIPTION,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): JSX.Element {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthSessionProvider>
          <ReactQueryProvider>
            <AuthStoreInitializer />
            <AuthGuard>
              <div className="min-h-screen flex">
                <SidebarWrapper />
                <main className="flex-1">{children}</main>
              </div>
            </AuthGuard>
          </ReactQueryProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
