import type { Metadata } from "next";
import "./globals.css";

import { Geist, Geist_Mono, Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import type { ReactNode, JSX } from "react";
import { AuthGuard } from "@/components/auth-guard";
import { AuthSessionProvider } from "@/providers/auth-session-provider";

const APP_METADATA_TITLE = "Create Next App";
const APP_METADATA_DESCRIPTION = "Generated by create next app";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: APP_METADATA_TITLE,
  description: APP_METADATA_DESCRIPTION,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): JSX.Element {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthSessionProvider>
          <AuthGuard>{children}</AuthGuard>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
